development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: locomotive_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: locomotive_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: locomotive_production
  pool:     5
  username: postgres
  password: postgres
  template: template0
